export interface LoanDto{
  id: number;
  firstName: string;
  middleName: string;
  lastName: string;
  sex: string;
  bankAccountNumber: string;
  employmentDate: Date;
  maritalStatus: string;
  confirmationDate: Date;
  totalEmployeeDeduction: number;
  nearestBranchName: string;
  nearestBranchCode: string;
  voteCode: string;
  voteName: string;
  NIN: string;
  designationCode: string;
  designationName: string;
  basicSalary: number;
  netSalary: number;
  oneThirdAmount: number;
  requestedAmount: number;
  desiredDeductibleAmount: number;
  retirementDate: number;
  termsOfEmployment: string;
  tenure: number;
  productCode: string;
  interestRate: number;
  processingFee: number;
  insurance: number;
  physicalAddress: string;
  emailAddress: string;
  mobileNumber: string;
  applicationNumber: string;
  loanPurpose: string;
  contractStartDate: Date;
  contractEndDate: Date;
  checkNumber: string;
  swiftCode: string;
  funding: string;
  loanType: string;
  essApprovalReason: string;
  disbursementDate: string;
  initialApproveDate: string;
  hroApproveDate: string;
  liquidationDate: string;
  employeeCancellDate: string;
  insuranceProcessFee: number;
  createdDate?: Date;
  paymentAdvice?: string; 
  paymentAdviceAttachment?: string

  // more takeover loan
  fsp1Code: string;
  fsp1SWIFTCode: string;
  fsp1BankAccount: string;
  fsp1BankAccountName: string;
  fsp1MNOChannel: string;
  fsp1LoanNumber: string;
  fsp1PaymentReferenceNumber: string;
  fsp1FinalPaymentDate: Date;
  takeOverAmount: number;

}